costmap:
  ros__parameters:
    update_frequency: 1.0 # Frequency at which the costmap is updated 1 Hz
    publish_frequency: 1.0 # Frequency at which the costmap is published 1 Hz
    global_frame: map
    robot_base_frame: base_footprint
    use_sim_time: true
    robot_radius: 0.1 # Radius of the robot's footprint is 10cm circular for costmap calculations
    resolution: 0.05 # Resolution of the costmap in meters (5cm per cell)
    always_send_full_costmap: true # Always send the full costmap to subscribers
    track_unknown_space: true # Track unknown space in the costmap
    # static_map: true
    # rolling_window: false
    # width: 10.0
    # height: 10.0

    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
      map_topic: "map"
      map_subscribe_transient_local: true
      
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      enable: true
      observation_sources: scan
      scan:
        topic: "/scan" # Topic for laser scan data
        data_type: "LaserScan"
        max_obstacle_height: 2.0 # Maximum height of obstacles to consider
        marking: true # Mark obstacles in the costmap
        clearing: true # Clear obstacles from the costmap
        combine_method: 1 # Combine multiple observations using "max" or 1
        raytrace_max_range: 3.0 # Maximum range for ray tracing in meters
        raytrace_min_range: 0.0 # Minimum range for ray tracing in meters
        obstacle_max_range: 2.5 # Maximum range for obstacles in meters
        obstacle_min_range: 0.0 # Minimum range for obstacles in meters

    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.55 # Radius for inflation in meters
      cost_scaling_factor: 3.0 # Scaling factor for inflation costs

    # obstacle_layer:
    #   observation_sources: scan
    #   scan:
    #     data_type: LaserScan
    #     topic: /scan
    #     marking: true
    #     clearing: true

    # inflation_layer:
    #   inflation_radius: 0.55
    #   cost_scaling_factor: 10.0